# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do

  desc "Deploy Podspecs to CocoaPods Trunk"
  lane :deploy do
    tag = "0.2.4"

    add_git_tag(
      tag: tag
    )

    # Push tag
    push_to_git_remote()

    # Deploy Podspecs
    Dir.chdir("..") do
      sh "pod trunk push GigouLib.podspec --allow-warnings"
    end
  end

end
